import { describe, it, expect } from "vitest";
import { MarkdownEpubConverter } from "../../../src/infrastructure/converter/markdown-epub-converter.js";
import { Title } from "../../../src/domain/values/title.js";
import { Author } from "../../../src/domain/values/author.js";
import { MarkdownContent } from "../../../src/domain/values/markdown-content.js";

function makeTitle(v: string) {
  const r = Title.create(v);
  if (!r.ok) throw new Error("bad setup");
  return r.value;
}

function makeAuthor(v: string) {
  const r = Author.create(v);
  if (!r.ok) throw new Error("bad setup");
  return r.value;
}

function makeContent(v: string) {
  const r = MarkdownContent.create(v);
  if (!r.ok) throw new Error("bad setup");
  return r.value;
}

describe("MarkdownEpubConverter", () => {
  const converter = new MarkdownEpubConverter();

  it("produces an EpubDocument with correct title", async () => {
    const result = await converter.toEpub(
      makeTitle("Test Book"),
      makeContent("# Chapter 1\n\nHello world."),
      makeAuthor("Claude"),
    );
    expect(result.ok).toBe(true);
    if (result.ok) {
      expect(result.value.title).toBe("Test Book");
      expect(result.value.sizeBytes).toBeGreaterThan(0);
      expect(result.value.buffer).toBeInstanceOf(Buffer);
    }
  });

  it("does not return a conversion error on valid input", async () => {
    const result = await converter.toEpub(
      makeTitle("Valid Book"),
      makeContent("# Hello\n\nSome content."),
      makeAuthor("Claude"),
    );
    // Explicitly assert no error — catches broken epub-gen-memory imports
    // that get swallowed by the try/catch and silently return err(...)
    expect(result.ok).toBe(true);
    if (!result.ok) {
      throw new Error(`Expected conversion to succeed but got error: ${result.error.message}`);
    }
  });

  it("produces a non-empty EPUB buffer with valid zip magic bytes", async () => {
    const result = await converter.toEpub(
      makeTitle("Magic Bytes Test"),
      makeContent("# Hello"),
      makeAuthor("Claude"),
    );
    expect(result.ok).toBe(true);
    if (result.ok) {
      // EPUB files are ZIP archives — first bytes must be PK\x03\x04
      expect(result.value.buffer[0]).toBe(0x50); // P
      expect(result.value.buffer[1]).toBe(0x4b); // K
      expect(result.value.buffer[2]).toBe(0x03);
      expect(result.value.buffer[3]).toBe(0x04);
    }
  });

  it("generates a URL-safe filename from title", async () => {
    const result = await converter.toEpub(
      makeTitle("Clean Architecture: A Guide"),
      makeContent("# Hello"),
      makeAuthor("Claude"),
    );
    expect(result.ok).toBe(true);
    if (result.ok) {
      // filename generated by infrastructure, not Title
      expect(result.value.title).toBe("Clean Architecture: A Guide");
    }
  });

  it("sanitizes script tags from markdown", async () => {
    const result = await converter.toEpub(
      makeTitle("XSS Test"),
      makeContent('Hello <script>alert("xss")</script> World'),
      makeAuthor("Claude"),
    );
    expect(result.ok).toBe(true);
    // The EPUB should be valid (no crash from malicious content)
  });

  it("preserves markdown structure (headings, lists, emphasis)", async () => {
    const md = [
      "# Heading 1",
      "## Heading 2",
      "- item 1",
      "- item 2",
      "",
      "**bold** and *italic*",
      "",
      "```\ncode block\n```",
    ].join("\n");

    const result = await converter.toEpub(
      makeTitle("Structure Test"),
      makeContent(md),
      makeAuthor("Claude"),
    );
    expect(result.ok).toBe(true);
    if (result.ok) {
      expect(result.value.sizeBytes).toBeGreaterThan(0);
    }
  });
});
